### ISSUE TITLE
May Updates

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/builders#10]
Checklist: 

- [x] FAQ Page Styles
- [x] Builder Section: Add Image
- [x] Summer Programs: Fix max-width of columns to match comp
- [x] Summer Programs: Set min-height/flex box to match comp
- [x] Mentor: Match Padding/Grid
- [x] Mentor: Add +More Functionality
- [x] FAQs: Make Sticky
- [ ] Browser Test
- [ ] Replace image
- [x] Reverse Firefox Footer on Homepage
- [x] Make Non-homepage Footers BLACK instead of PURPLE
- [x] Move Q+A Promo into Hero on Homepage
- [x] Style Mission Links as Reverse Btns (Keep Font-size)
- [x] Replace Testimonial Link in Mission Section with "How to Apply" 
- [x] Add Social Links / Slack
- [x] Restyle Testimonials
- [x] Fix Page Title (Remove Spring Labs) 
- [x] Who we fund  |  How to apply?
- [x] Vision in navbar > Who We Fund 
- [x] FB / TW / IG —> SL / Twitter Join us on Slack and Twitter
- [x] kill “Our startups / Testimonial”
- [x] Mentorship Program > Visiting Mentors  / Mentors
- [x] Kill the current “visiting mentors” text at the bottom
- [x] Remove RSVP Button / Add Hyperlink to Hero Paragraph
- [x] Fix image ratios (Bart) 
- [x] Sticky Fix / Subpage
- [x] Remove Underline form Button style 
- [x] Reduce padding on mission btns (33%) 
- [x] Add icons / non-brand color (circles) 16px height (to left of word)  
- [x] Add new person as first position / kill link 

Home: 
![Home](https://user-images.githubusercontent.com/2692333/81622905-d7615580-93b7-11ea-8d97-4115b9549a1b.png)

FAQs: 

![FAQs](https://user-images.githubusercontent.com/2692333/81622850-b7319680-93b7-11ea-96e4-c4080b6dfddb.png)

**Comment by Aakash2408** [comment]
Have you made these changes? They are not showing on website.

**Comment by bdecrem** [comment]
yes, something we are working on that's not yet finalized/published.

**Comment by Aakash2408** [comment]
I would like to contribute to this webpage :)
